/**
 * Free EVM keypair for Telegraph x402 on Base Sepolia (eip155:84532).
 * Usage:
 *   pnpm keys:evm
 *   pnpm keys:evm --write
 */
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { writeFileSync, readFileSync, existsSync } from "fs";

const privateKey = generatePrivateKey();
const account = privateKeyToAccount(privateKey);

console.log("\n=== Free EVM key (Base Sepolia) ===\n");
console.log("Address:", account.address);
console.log("EVM_PRIVATE_KEY:", privateKey);
console.log("\n1) Base Sepolia ETH (gas): https://www.alchemy.com/faucets/base-sepolia  or  https://faucet.quicknode.com/base/sepolia");
console.log("2) Base Sepolia USDC: Circle faucet https://faucet.circle.com  (select Base Sepolia + USDC)");
console.log("   USDC contract: 0x036CbD53842c5426634e7929541eC2318f3dCF7e");
console.log("3) Set FORCE_MOCK=false and restart pnpm dev\n");
console.log("NEVER commit this key. Use a burner only.\n");

if (process.argv.includes("--write")) {
  const path = ".env.local";
  let existing = existsSync(path) ? readFileSync(path, "utf8") : "";
  const lines = [
    "",
    "# Generated by pnpm keys:evm --write",
    `EVM_PRIVATE_KEY=${privateKey}`,
    "EVM_NETWORK=eip155:84532",
    "TELEGRAPH_NODE_URL=http://13.237.89.59:7044",
    "FORCE_MOCK=false",
    "",
  ].join("\n");

  if (/^EVM_PRIVATE_KEY=/m.test(existing)) {
    existing = existing.replace(/^EVM_PRIVATE_KEY=.*$/m, `EVM_PRIVATE_KEY=${privateKey}`);
    if (!/^EVM_NETWORK=/m.test(existing)) existing += "\nEVM_NETWORK=eip155:84532\n";
    if (!/^TELEGRAPH_NODE_URL=/m.test(existing))
      existing += "\nTELEGRAPH_NODE_URL=http://13.237.89.59:7044\n";
    if (!/^FORCE_MOCK=/m.test(existing)) existing += "\nFORCE_MOCK=false\n";
    writeFileSync(path, existing);
    console.log("Updated EVM_PRIVATE_KEY in .env.local");
  } else {
    writeFileSync(path, existing + lines);
    console.log("Appended EVM key + defaults to .env.local");
  }
}
